# Generated by Django 2.2.20 on 2021-07-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('idade', models.IntegerField(max_length=3)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
    ]
